### ISSUE TITLE
segmentation fault (core dumped) when running predict.py in af2_binder_design

### ISSUE THREAD

**Issue by MadelineMartin** [nrbennet/dl_binder_design#69]
I ran the importtest for af2_binder_design and it passed, but when I run predict.py, I get a segmentation fault. I narrowed it down to it being that I am running out of memory when importing packages, specifically jax.numpy and pyrosetta, but I am on a 40gb GPU and I have tried as high as 128G of memory on my university's HPC. How do I overcome this memory issue?

My jax version is 0.4.23 build pypi_0, channel pypi
jaxlib 0.4.23+cuda12.cudann89, pypi_0, pypi
jmp 0.0.4 pypi_0, pypi
pyrosetta 2024.01+release.00b7914, py311_0, graylab

Thanks in advance for your help!

**Comment by MadelineMartin** [comment]
I fixed this problem. I had to download an older version of PyRosetta. I downloaded version 2023.49+release.9891f2c59fb. 
I downloaded the proper tar.bz2 file from the coast mirror on pyrosetta.org, unpacked it in the af2_binder_design conda environment, and installed it using "python setup.py install" inside the af2_binder_design environment.

**Comment by Avidhoot26** [comment]
Hey,
Could you clarify which older version of pyRosetta exactly, did you download to solve this.....

**Comment by MadelineMartin** [comment]
> Hey, Could you clarify which older version of pyRosetta exactly, did you download to solve this.....

Version: 2023.49+release.9891f2c59fb

Let me know if you need more info!

**Comment by Avidhoot26** [comment]
Could you send me the link of where you got this (downloaded it) from.

I tried to get this version from here (for linux): https://west.rosettacommons.org/pyrosetta/conda/release/linux-64/
([pyrosetta-2023.49+release.9891f2c-py37_0.tar.bz2](https://west.rosettacommons.org/pyrosetta/conda/release/linux-64/pyrosetta-2023.49+release.9891f2c-py37_0.tar.bz2)
However when I extracted it, I couldn't find the setup.py file in this.
Thanks!

**Comment by Avidhoot26** [comment]
I managed to download it using conda install pyrosetta=2023.49+release.9891f2c
However the segmentation fault still persists. Any suggestions on how I could solve it.
